import './scripts/modal/modal.js';
import './scripts/renderFilmCard.js';
import './scripts/onOpenLibrary.js';
import './scripts/searsh.js';
import './scripts/modal/footerModal.js';
import './scripts/localStorageApi.js';
import './scripts/pagination.js';
import './scripts/addQueue';
import './scripts/to-top-btn'